# Generated by Django 3.0 on 2019-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_blog', models.CharField(default='', max_length=200)),
                ('judul_blog', models.CharField(default='', max_length=200)),
                ('isi_blog', models.TextField(default='')),
                ('tanggal_blog', models.DateField(verbose_name='tanggal blog')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_mentee', models.CharField(default='', max_length=200)),
                ('nama_mentee', models.CharField(default='', max_length=200)),
                ('quote_mentee', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_mentor', models.CharField(default='', max_length=200)),
                ('nama_mentor', models.CharField(default='', max_length=200)),
                ('pengalaman_mentor', models.CharField(default='', max_length=200)),
                ('quote_mentor', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
